import {NgModule} from '@angular/core';
import {
    MatCardModule,
    MatDialogModule,
    MatSnackBarModule,
    MatProgressSpinnerModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatInputModule,
    MatStepperModule,
    MatListModule,
    MatIconModule,
    MatPaginatorModule,
    MatDatepickerModule,
    MatButtonModule,
    MatTooltipModule,
    MatSlideToggleModule,
    MatRadioModule,
    MatToolbarModule,
    MatSortModule,
    MatMenuModule,
    MatSelectModule,
    MatChipsModule,
    MatTableModule,
    MatGridListModule,
    MatSidenavModule,
    MatCheckboxModule
} from '@angular/material';
import {MatDividerModule} from '@angular/material/divider';
import {MatTabsModule} from '@angular/material/tabs';

@NgModule({
    imports: [
        MatButtonModule,
        MatToolbarModule,
        MatCardModule,
        MatDialogModule,
        MatSnackBarModule,
        MatProgressSpinnerModule,
        MatExpansionModule,
        MatFormFieldModule,
        MatInputModule,
        MatStepperModule,
        MatListModule,
        MatIconModule,
        MatPaginatorModule,
        MatDatepickerModule,
        MatButtonModule,
        MatTooltipModule,
        MatSlideToggleModule,
        MatRadioModule,
        MatToolbarModule,
        MatSortModule,
        MatMenuModule,
        MatSelectModule,
        MatChipsModule,
        MatTableModule,
        MatGridListModule,
        MatSidenavModule,
        MatCheckboxModule,
        MatDialogModule,
        MatTabsModule,
    ],
    exports: [
        MatButtonModule,
        MatToolbarModule,
        MatCardModule,
        MatDialogModule,
        MatSnackBarModule,
        MatProgressSpinnerModule,
        MatExpansionModule,
        MatFormFieldModule,
        MatInputModule,
        MatStepperModule,
        MatListModule,
        MatIconModule,
        MatPaginatorModule,
        MatDatepickerModule,
        MatButtonModule,
        MatTooltipModule,
        MatSlideToggleModule,
        MatRadioModule,
        MatToolbarModule,
        MatSortModule,
        MatMenuModule,
        MatSelectModule,
        MatChipsModule,
        MatTableModule,
        MatGridListModule,
        MatSidenavModule,
        MatCheckboxModule,
        MatDividerModule,
        MatTabsModule,
    ]
})
export class MaterialModule {}
